# Acknowledgements {-}

If you find something you like in this book, I can probably trace its origin to one of the many people who helped me pull it all together. I want to thank them for this good work and absolve them from responsibility for any errors.

I'll start with my students. I've had the privilege of working alongside many fantastic graduate student teaching assistants over the years, including Kaitlin Saxton, Kathleen Perry, Olivia Fletcher, Jenae Logan, Hiwot Zewdie, Siddhesh Zadey, Anfal Adbelgadir, Madeline Wilkerson, and Lori Babb. Each one of them helped me to make the course stronger. So have the students in my undergraduate and graduate courses. Student feedback was largely anonymous, but I can thank a few people by name: Kelsey Sumner, Karly Gregory, Qian Yudong, Christina Schmidt, Aidan Floyd, Shannon Houser, TODO add names from qualtrics.

Next I'd like to thank my colleagues at Duke who provided valuable support. Duke librarians Megan Von Isenburg and Hannah Rozear set me straight on literature searches. Gavin Yamey helped me understand what we do and don't know about funding for global health research. Liz Turner and Joe Egger have fielded more technical questions that I can count.

On the institutional side, I'm grateful to the Learning Innovations team for coming on this journey with me, including Andrea Novicki, Heather Hans, William Williamson, Ben Richardson, Michael Blair, and Quentin Ruiz-Esparza. Thanks as well to Mary Story and Sarah Martin for supporting me from within the Duke Global Health Institute, and to the Duke OIT staff, including Zach Hill, Jeremy Hopkins, and Richard Biever, who helped me to get domains and servers working, despite my efforts to thwart their progress.

I used R and numerous tools from RStudio to create this book and course materials. I'm very thankful for their support to educators like me. The same goes for members of the open source community who create and maintain awesome software, including Yihui Xie (`bookdown`), Mike Smith (`msmbstyle`), Jonathan Weisberg (css help), and many others.

Several scholars were very generous with their time and agreed to let me interview them for the book. Thanks to Daniel Halperin, Salim Abdulla, Paul Garner, Wendy O'Meara, and Vikram Patel. Other colleagues shared comments on drafts, including Daniel Lakens and Solomon Kurz.

I never intended to publish this book as anything other than a course website, but I attended a talk by David Grubbs at Chapman & Hall/CRC that encouraged me to submit a book proposal. I'm sure glad I did. He sent the initial chapters out for review, and the anonymous reviewers helped me to spot some holes that needed filling. I thank them for their service.

Finally, I'd like to thank my wife, Eve, and my parents for more support and encouragement than one person deserves.
